### ISSUE TITLE
cant start

### ISSUE THREAD

**Issue by djraymond** [daccakareem/qb-drone#3]
if i put it in my server it dont start

**Comment by krrm1** [comment]
i will test it again

**Comment by krrm1** [comment]
and you can download it

**Comment by djraymond** [comment]
do you have discord to help me

**Comment by krrm1** [comment]
yes check profile

**Comment by krrm1** [comment]
its easy fix
i will redoawload it

**Comment by krrm1** [comment]
done delete the old script and download the new one form here https://github.com/arabcodingteam/arabcodingteam-drone

and ensure all the script so it can work
